services:
- type: pserv
  name: mysql
  plan: standard
  env: docker
  repo: https://github.com/render-examples/mysql.git
  disk:
    name: mysql
    mountPath: /var/lib/mysql
    sizeGB: 10
  envVars:
  - key: MYSQL_DATABASE
    value: mysql
  - key: MYSQL_USER
    value: mysql
  - key: MYSQL_PASSWORD
    generateValue: true
  - key: MYSQL_ROOT_PASSWORD
    generateValue: true

- type: web
  name: wordpress
  env: docker
  repo: https://github.com/render-examples/wordpress.git
  disk:
    name: wordpress
    mountPath: /var/www/html
    sizeGB: 10
  envVars:
    - key: WORDPRESS_DB_HOST
      fromService:
        name: mysql
        type: pserv
        property: host
    - key: WORDPRESS_DB_NAME
      fromService:
        name: mysql
        type: pserv
        envVarKey: MYSQL_DATABASE    
    - key: WORDPRESS_DB_USER
      fromService:
        name: mysql
        type: pserv
        envVarKey: MYSQL_USER    
    - key: WORDPRESS_DB_PASSWORD
      fromService:
        name: mysql
        type: pserv
        envVarKey: MYSQL_PASSWORD    
  


